#!/usr/bin/env php
<?php

/**
 * Yii console bootstrap file.
 */

require __DIR__ . '/vendor/autoload.php';

use Dotenv\Dotenv;
use yii\helpers\ArrayHelper;

// Load environments configuration
$env = Dotenv::create(__DIR__);
try {
    $env->load();
} catch (\Exception $error) {
    alert("App environment initialization failed");
    die();
}

define('YII_DEBUG', env('APP_DEBUG')); // false
define('YII_ENV', env('APP_ENV')); // prod

// Load Yii application requirements
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/config/aliases.php';

$config = require __DIR__ . '/config/test/console.php';

// Try to start application
$application = new yii\console\Application($config);
$exitCode = $application->run();

exit($exitCode);